export const VIEW = {
    INIT: "INIT",
    LOADING: "LOADING",
    STARTED: "STARTED",
    SUBMITTING: 'SUBMITTING',
    ENDED: 'ENDED',
}

export const ACTION = {
    LOAD_QUIZ: 'LOAD_QUIZ',
    START_QUIZ: 'START_QUIZ',
    START_QUIZ_FAIL: 'START_QUIZ_FAIL',
    SELECT_ANSWER: 'SELECT_ANSWER',
    START_SUBMIT_QUIZ: 'START_SUBMIT_QUIZ',
    FAIL_SUBMIT_QUIZ: 'FAIL_SUBMIT_QUIZ',
    SHOW_REPORT: 'SHOW_REPORT',
    RESET: 'RESET',
}
